services:
  db:
    image: postgres:13
    container_name: db
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - static:/app/static
      - media:/app/media
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 kittygram_backend.wsgi"

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - frontend_build:/app/build
    depends_on:
      - backend
    restart: always

  gateway:
    build: ./nginx
    container_name: gateway
    ports:
      - "8080:80"
    volumes:
      - static:/static
      - media:/media
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  pg_data:
  static:
  media:
  frontend_build:
